version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt   
      - run:
          name: Run tests with BrowserStack
          command: |
            python -m venv env
            source env/bin/activate
            pip install -r requirements.txt
            browserstack-sdk python ./tests/test.py
workflows:
  version: 2
  test:
    jobs:
      - test
