version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/Scripts/activate
            pip install -r requirements.txt
      - run:
          name: Run tests with BrowserStack
          command: |
            . venv/Scripts/activate
            python

workflows:
  version: 2
  test:
    jobs:
      - test
